### ISSUE TITLE
ikonky pre typy kniznic

### ISSUE THREAD

**Issue by petervojtek** [Infolovec/mapakniznic.sk#5]
kniznica: http://www.flaticon.com/free-icon/home-icon-silhouette_69524#term=house&page=1&position=9
letna citaren: http://www.flaticon.com/free-icon/reading_161274#term=library&page=1&position=24
bibliobox: http://www.flaticon.com/free-icon/cube_153737#term=cube&page=1&position=9
knizna budka: http://www.flaticon.com/free-icon/flag-triangle-pointing-left_56904#term=triangle&page=6&position=34

typ zobrazovat len ako typ spolocne pre vsetky druhy objektov:
typ: verejná knižnica
typ: vedecká knižnica
typ: špeciálna knižnica
typ: školská knižnica
typ: akademická knižnica
typ: bibliobox
typ: knižná búdka
typ: letná čitáreň

**Comment by martaduskova** [comment]
ok

**Comment by petervojtek** [comment]
je to nasadene: https://mapakniznic.sk
